### ISSUE TITLE
app-specific passwords

### ISSUE THREAD

**Issue by FeLiiix** [iobroker-community-adapters/ioBroker.find-my-iphone#11]
Hi
Is it possible to use app-specific passwords?
The adapter turns green but no objects were generated.
Thanks

**Comment by Xyolyp** [comment]
Hi @FeLiiix 
I'm a new iPhone user and I never developed an adapter for ioBroker but I would like to use this adapter and in my installation no objects are generated, too.
Can you explain what you mean by app-specific passwords so that I can have a look into it and maybe find a way to implement it if it resolves my issue, too?
Thanks in advance
